version: '3'
services:
    php:
        container_name: php
        image: jdequeant/rpi-alpine-php7fpm:latest
        volumes:
            - /home/pirate/containers/jdequeant/rpi-alpine-h2o/var/www:/var/www
    h2o:
        container_name: h2o
        image: jdequeant/rpi-alpine-h2o:php-fpm
        ports: 
            - 80:80
            - 443:443
        environment:
            FPM_HOST: php:9000
            XDEBUG_CONFIG: remote_host=172.22.0.1
        volumes:
            - /home/pirate/containers/jdequeant/rpi-alpine-h2o/etc/h2o:/etc/h2o
            - /home/pirate/containers/jdequeant/rpi-alpine-h2o/var/www:/var/www
        links:
            - php
